export const ADMIN_UPDATE_USER_REQUEST = "ADMIN_UPDATE_USER_REQUEST"
export const ADMIN_UPDATE_USER_SUCCESS = "ADMIN_UPDATE_USER_SUCCESS"
export const ADMIN_UPDATE_USER_FAIL = "ADMIN_UPDATE_USER_FAIL"

export const ADMIN_DELETE_USER_REQUEST = "ADMIN_DELETE_USER_REQUEST"
export const ADMIN_DELETE_USER_SUCCESS = "ADMIN_DELETE_USER_SUCCESS"
export const ADMIN_DELETE_USER_FAIL = "ADMIN_DELETE_USER_FAIL"

export const ADMIN_ORDERS_LIST_REQUEST = "ADMIN_ORDERS_LIST_REQUEST"
export const ADMIN_ORDERS_LIST_SUCCESS = "ADMIN_ORDERS_LIST_SUCCESS"
export const ADMIN_ORDERS_LIST_FAIL = "ADMIN_ORDERS_LIST_FAIL"

export const ADMIN_SHIPPING_UPDATE_REQUEST = "ADMIN_SHIPPING_UPDATE_REQUEST"
export const ADMIN_SHIPPING_UPDATE_SUCCESS = "ADMIN_SHIPPING_UPDATE_SUCCESS"
export const ADMIN_SHIPPING_UPDATE_FAIL = "ADMIN_SHIPPING_UPDATE_FAIL"

export const ADMIN_DELIVERED_UPDATE_REQUEST = "ADMIN_DELIVERED_UPDATE_REQUEST"
export const ADMIN_DELIVERED_UPDATE_SUCCESS = "ADMIN_DELIVERED_UPDATE_SUCCESS"
export const ADMIN_DELIVERED_UPDATE_FAIL = "ADMIN_DELIVERED_UPDATE_FAIL"
