export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_GET_ITEMS_REQUEST = "ORDER_GET_ITEMS_REQUEST"
export const ORDER_GET_ITEMS_SUCCESS = "ORDER_GET_ITEMS_SUCCESS"
export const ORDER_GET_ITEMS_FAIL = "ORDER_GET_ITEMS_FAIL"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"
